[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "fitness_tracker.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
